### ISSUE TITLE
-Wimplicit-fallthrough  common/SerialIO.cpp  line 231 m_tio.c_cflag |= PARODD; // break;

### ISSUE THREAD

**Issue by juanea** [neobotix/neo_relayboard_v2-2#10]
I am trying to build the neo_simulation2 with the mp_400 in the humble distro.
after following the documentation and cloning all the packages I am building the workspace with `colcon build --symlink-install`

```
neo_relayboard_v2-2/common/src/SerialIO.cpp:231:39: warning: this statement may fall through [-Wimplicit-fallthrough=]
  231 |                         m_tio.c_cflag |= PARODD;```
After line 231 it has the break for the switch case commented.
 //break;  // break must not be active here as we need the combination of PARODD and PARENB on odd parity.
```
In the CMakeList.txt it has this option to treat warnings as errors

```
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()
```

After commenting the above 3 lines in the CMakeList.txt it works.

**Comment by padhupradheep** [comment]
Thanks for the report, but they are just warnings and not errors. You can see that the build has been completed at the end.  We plan to suppress the warnings very soon. 

BTW, you do not have to install the relayboard package for simulation, as we do not simulate the relayboard. 

Closing the issue!
